[project]
name = "playwright-changesets"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "playwright==1.51.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "pip>=25.1",
]
